# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: cullleaves
  alternativeNames: ~
  tags:
    - miscellaneous
    - cosmetic
    - optifine-alternative
  packages:
    - packageId: cullleaves.TeamMidnightDust
      loaders:
        - fabric
