# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: modmenu
  alternativeNames:
    - mod-menu
  tags:
    - utility
    - miscellaneous
  packages:
    - packageId: modmenu.TerraformersMC
      loaders:
        - fabric
