# yaml-language-server: $schema=../../../doc/validation-schemas/5.0-alpha.2/modId-manifest.json
manifestSpecVersion: "5.0-alpha.2"
tags:
  - library
  - miscellaneous
  - api
packages:
  - publisher: BradBot_1
