# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: fdlink
  alternativeNames:
    - fabric-discord-link
  tags:
    - utility
    - miscellaneous
    - information
  packages:
    - packageId: fdlink.CatCore
      loaders:
        - fabric
