# yaml-language-server: $schema=../../../../../../doc/validation-schemas/5.0-alpha.2/version-manifest.json



- loaders:
    - fabric
  minecraftVersions:
    - "1.18"
  environment:
    server: unsupported
    client: required
  channel: release
  depends:
    - packageId: fabric.FabricMC
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "356461"
  license: MIT
  fileType: jar
  md5: 4226ee989324895fa0c1efb0619a523d
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/logical-zoom/files/3542015
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/logical-zoom/download/3542015/file
    sourceControl: ~
    others: ~
