# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: fabric-language-kotlin
  alternativeNames: ~
  tags:
    - library
    - api
  packages:
    - packageId: fabric-language-kotlin.FabricMC
      loaders:
        - fabric
