# yaml-language-server: $schema=../../../../../../doc/validation-schemas/5.0-alpha.2/version-manifest.json

manifestSpecVersion: "5.0-alpha.2"
variants:
  - loaders:
      - fabric
    minecraftVersions:
      - "1.17.1"
      - "1.17"
    environment:
      server: unsupported
      client: required
    channel: release
    depends:
      - packageId: fabric.FabricMC
        version: "*"
    bundles: ~
    breaks:
      - packageId: optifabric.Chocohead
        version: "*"
    conflicts: ~
    recommends: ~
    thirdPartyIds:
      modrinth: "PRN43VSY"
      curseforge: "533006"
    license: LGPL-3.0
    fileType: jar
    md5: 984a49fd7f71a29a4f4f299508e7bdc8
    downloadPageUrls:
      modrinth: https://modrinth.com/mod/animatica/version/NXTzSfcj
      curseforge: https://www.curseforge.com/minecraft/mc-mods/animatica/files/3478564
      sourceControl: ~
      others: ~
    fileUrls:
      modrinth: https://cdn.modrinth.com/data/PRN43VSY/versions/0.1+1.17/animatica-0.1+1.17.jar
      curseforge: https://www.curseforge.com/minecraft/mc-mods/animatica/download/3478564/file
      sourceControl: ~
      others: ~
