# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: hydrogen
  alternativeNames:
    - hydrogen-fabric
  tags:
    - utility
    - performance
  packages:
    - packageId: hydrogen.CaffeineMC
      loaders:
        - fabric
