# yaml-language-server: $schema=../../../../doc/validation-schemas/5.0-alpha.2/publisher-manifest.json

manifestSpecVersion: "5.0-alpha.2"
publisher: Grondag
loaders:
  - "fabric"
iconUrls:
  - https://media.forgecdn.net/avatars/thumbnails/215/643/64/64/636998432658345950.png
status: active
updatedAlternatives: ~
names:
  official: Clear Skies
  others: ~
description: Makes horizon and fog colors match the sky
authors:
  - name: Grondag
home: https://www.curseforge.com/minecraft/mc-mods/clear-skies
source: https://github.com/grondag/clear-skies
issues: https://github.com/grondag/clear-skies/issues
support: https://discord.gg/7NaqR2e
wiki: ~
chats:
  discord: https://discord.gg/7NaqR2e
  irc: ~
  others: ~
versions:
  - version: "1.5.70"
  - version: "1.5.57"
