# yaml-language-server: $schema=../../../doc/validation-schemas/4.0/lookup-table.json

- id: fabulousclouds
  alternativeNames:
    - fabulous-clouds
  tags:
    - cosmetic
    - miscellaneous
    - optifine-alternative
  packages:
    - packageId: fabulousclouds.misterslime
      loaders:
        - fabric
